name: Ennustaja

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  calculate_audience:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is important - add write permission

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run AnalysoiOttelut.py Script
      run: python Scripts/AnalysoiOttelut.py

    - name: Verify Script run
      run: cat AnalysoidutOttelut.md

    - name: Commit and push if changes
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add AnalysoidutOttelut.md
        git commit -m "Update analyzed matches" || echo "No changes to commit"
        git push
