name: Ennustaja

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  calculate_audience:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run AnalysoiOttelut.py Script
      run: python Scripts/AnalysoiOttelut.py

    - name: Verify Script run
      run: cat AnalysoidutOttelut.md

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add AnalysoidutOttelut.md
        git diff --staged --quiet || git commit -m "Update analyzed matches $(date)"
        git push origin HEAD:main || git push origin HEAD:master
