name: Päivittäinen Ottelulaskuri

on:
  schedule:
    # Asetetaan suoritusajankohta joka päivä klo 22:00 UTC
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  update_future_games:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Varmista, että tämä versio sopii koodillesi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Tulevatottelut.py script
      run: python scripts/Tulevatottelut.py

    - name: Commit and push if changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add Tulevatottelut.md  # Varmista, että lisäät oikean tiedoston
        git commit -m "Update upcoming games data" || echo "No changes to commit"
        git push
