name: Update Audience Statistics

on:
  schedule:
    - cron: '0 */6 * * *'  # Suoritetaan joka 6. tunti
  workflow_dispatch:  # Mahdollistaa manuaalisen käynnistyksen

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run audience calculator
      run: python Scripts/Yleisölaskuri.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add Yleisö2025.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Päivitetty yleisötilastot $(date +'%Y-%m-%d')" && git push)
