name: Korjaa nollalla jako

on:
 schedule:
    # Asetetaan suoritusajankohta joka päivä klo 22:00 UTC
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  fix-division:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fix division by zero
        run: |
          sed -i 's|total_home_audience / home_games|total_home_audience / home_games if home_games > 0 else 0|g' Scripts/Yleisölaskuri.py
          sed -i 's|total_away_audience / away_games|total_away_audience / away_games if away_games > 0 else 0|g' Scripts/Yleisölaskuri.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          pip install -r requirements.txt
          
      - name: Run script
        run: python Scripts/Yleisölaskuri.py
        
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Scripts/Yleisölaskuri.py Yleisö*.md
          git commit -m "Korjattu nollalla jakaminen" || echo "No changes to commit"
          git push || echo "Nothing to push"
