name: Veikkausliiga 2025 Yleisölaskuri

on:
  schedule:
    - cron: '0 20 * * *'  # Suoritetaan joka päivä klo 20:00 UTC
  workflow_dispatch:  # Mahdollistaa manuaalisen käynnistyksen

jobs:
  calculate_audience:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Fix script
      run: |
        # Ladataan uusin versio skriptistä
        curl -o Scripts/Yleisölaskuri.py https://raw.githubusercontent.com/OMAKAUKKELISI/Veikkausliiga2025/main/Scripts/Yleisolaskuri.py || {
          echo "Korjatun version lataus epäonnistui"
          exit 1
        }
        
        # Varmistetaan tiedoston olemassaolo
        ls -la Scripts/Yleisölaskuri.py

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Yleisölaskuri.py script
      run: python Scripts/Yleisölaskuri.py

    - name: Commit and push if changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add Yleisö2025.md
        git diff --cached --quiet || git commit -m "Automaattinen päivitys: $(date +'%Y-%m-%d %H:%M')"
        git push
