name: Korjaa nollalla jako

on:
  schedule:
    # Asetetaan suoritusajankohta joka päivä klo 22:00 UTC
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  fix-division:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Run the Python script directly with nollalla jako handling
      - name: Run script
        run: |
          cd Scripts
          python Yleisölaskuri.py
          mv PelatutOttelut.md ../ || echo "File was not created in the Scripts directory"
          cd ..
        
      # Commit changes if any
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add PelatutOttelut.md Yleisö*.md || echo "Nothing to add"
          git commit -m "Päivitetty yleisö- ja ottelutiedot" || echo "No changes to commit"
          git push || echo "Nothing to push"
