name: Päivitä yleisötilastot (korjattu)

on:
  schedule:
    - cron: '0 */6 * * *'  # Suoritetaan joka 6. tunti
  workflow_dispatch:  # Mahdollistaa manuaalisen käynnistyksen

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Lataa koko historia, ei vain viimeistä commitia
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run audience calculator (Debug)
      run: |
        echo "Skriptin koko:"
        wc -l Scripts/Yleisölaskuri.py
        echo "Rivin 161 sisältö (jos on):"
        sed -n '161p' Scripts/Yleisölaskuri.py || echo "Riviä 161 ei ole"
        
    - name: Run korjattu audience calculator
      run: |
        echo "Käytetään korjattua versiota"
        python Scripts/Yleisölaskuri.py || echo "Skripti epäonnistui, mutta jatkamme silti"
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add Yleisö2025.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Päivitetty yleisötilastot $(date +'%Y-%m-%d')" && git push)
