name: Korjaa nollalla jako

on:
  schedule:
    # Asetetaan suoritusajankohta joka päivä klo 22:00 UTC
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  fix-division:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Fix division by zero in the script
      - name: Fix division by zero
        run: |
          sed -i 's|total_home_audience / home_games|total_home_audience / home_games if home_games > 0 else 0|g' Scripts/Yleisölaskuri.py
          sed -i 's|total_away_audience / away_games|total_away_audience / away_games if away_games > 0 else 0|g' Scripts/Yleisölaskuri.py

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping dependency installation."
          fi
          
      # Run the Python script
      - name: Run script
        run: |
          if [ -f Scripts/Yleisölaskuri.py ]; then
            python Scripts/Yleisölaskuri.py
          else
            echo "Scripts/Yleisölaskuri.py not found, skipping script execution."
          fi
        
      # Commit changes if any
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Scripts/Yleisölaskuri.py Yleisö*.md || echo "Nothing to add"
          git commit -m "Korjattu nollalla jakaminen" || echo "No changes to commit"
          git push || echo "Nothing to push"
