name: Korjaa nollalla jako ja päivitä yleisötilastot

on:
  workflow_dispatch:  # Manuaalinen käynnistys

jobs:
  fix-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Fix division by zero in line 161
      run: |
        # Näytetään rivin 161 sisältö
        echo "Rivin 161 sisältö ennen korjausta:"
        sed -n '161p' Scripts/Yleisölaskuri.py
        
        # Korjataan vain virheellinen rivi
        sed -i '161s/.*file\.write(f"#### Keskiarvoyleisömäärä per peli: {total_home_audience \/ home_games:.2f} ({home_games} peliä)\\n").*/        if home_games > 0:\n            file.write(f"#### Keskiarvoyleisömäärä per peli: {total_home_audience \/ home_games:.2f} ({home_games} peliä)\\n")\n        else:\n            file.write("#### Keskiarvoyleisömäärä per peli: 0.00 (0 peliä)\\n")/' Scripts/Yleisölaskuri.py
        
        # Tarkistetaan korjauksen onnistuminen
        echo "Rivit 160-165 korjauksen jälkeen:"
        sed -n '160,165p' Scripts/Yleisölaskuri.py
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run audience calculator
      run: python Scripts/Yleisölaskuri.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add Scripts/Yleisölaskuri.py Yleisö2025.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Korjattu nollalla jako" && git push)
